Repository projekt0n/github-nvim-theme, pull requests merged in 2021-07, with the labels that each got.

#1 Init
  .github/workflows/lint.yml
  .lua-format
  .luacheckrc
  CHANGELOG.md
  Makefile
  README.md
  colors/github.vim
  extras/alacritty_github_dark.yml
  extras/alacritty_github_dimmed.yml
  extras/alacritty_github_light.yml
  extras/kitty_github_dark.conf
  extras/kitty_github_dimmed.conf
  extras/kitty_github_light.conf
  lua/github-theme/colors.lua
  lua/github-theme/config.lua
  lua/github-theme/extra/alacritty.lua
  lua/github-theme/extra/init.lua
  lua/github-theme/extra/kitty.lua
  lua/github-theme/hsluv.lua
  lua/github-theme/init.lua
  lua/github-theme/theme.lua
  lua/github-theme/util.lua
  lua/lualine/themes/github.lua
  queries/lua/highlights.scm
  queries/typescript/highlights.scm
Labels: documentation, enhancement

#6 Some terminal fixes
  CHANGELOG.md
  extras/alacritty_github_dark.yml
  extras/alacritty_github_dimmed.yml
  extras/alacritty_github_light.yml
  extras/kitty_github_dark.conf
  extras/kitty_github_dimmed.conf
  extras/kitty_github_light.conf
  lua/github-theme/extra/alacritty.lua
  lua/github-theme/extra/kitty.lua
Labels: documentation, enhancement

#17 fixed #11: Added option to customize statusline background with `colors.bg_statusline`
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: enhancement

#21 fixed #10: illuminate highlights
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: documentation, enhancement

#27 `folded` colors are configurable
  CHANGELOG.md
  README.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: documentation

#28 Neogit support (releated to #16)
  CHANGELOG.md
  README.md
  lua/github-theme/theme.lua
Labels: documentation, enhancement

#31 lualine `command` background fixed #30
  CHANGELOG.md
  lua/lualine/themes/github.lua
Labels: assigned, documentation

#14 💄 Add iterm themes
  extras/iterm_github_dark.itermcolors
  extras/iterm_github_dimmed.itermcolors
  extras/iterm_github_light.itermcolors
  lua/github-theme/extra/init.lua
  lua/github-theme/extra/iterm.lua
Labels: Planned, assigned, enhancement

#32 Additional plugin support (releated to #16)
  CHANGELOG.md
  README.md
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#34 Make window-separator(`VertSplit`) highlight bright (related to #16)
  CHANGELOG.md
  lua/github-theme/colors.lua
Labels: assigned, documentation

#33 Add generating of Konsole themes
  extras/konsole_github_dark.colorscheme
  extras/konsole_github_dimmed.colorscheme
  extras/konsole_github_light.colorscheme
  lua/github-theme/extra/init.lua
  lua/github-theme/extra/konsole.lua
Labels: assigned, enhancement

#37 Regenerate terminal themes according to `colors.lua`
  CHANGELOG.md
  README.md
  extras/alacritty_github_dark.yml
  extras/alacritty_github_dimmed.yml
  extras/alacritty_github_light.yml
  extras/iterm_github_dark.itermcolors
  extras/iterm_github_dimmed.itermcolors
  extras/iterm_github_light.itermcolors
  extras/kitty_github_dark.conf
  extras/kitty_github_dimmed.conf
  extras/kitty_github_light.conf
  extras/konsole_github_dark.colorscheme
  extras/konsole_github_dimmed.colorscheme
  extras/konsole_github_light.colorscheme
  lua/github-theme/extra/iterm.lua
  lua/github-theme/extra/kitty.lua
Labels: assigned, documentation, enhancement

#39 Fix/extra themes
  extras/alacritty/dark.yml
  extras/alacritty/dimmed.yml
  extras/alacritty/light.yml
  extras/iterm/dark.itermcolors
  extras/iterm/dimmed.itermcolors
  extras/iterm/light.itermcolors
  extras/kitty/dark.conf
  extras/kitty/dimmed.conf
  extras/kitty/light.conf
  extras/konsole/dark.colorscheme
  extras/konsole/dimmed.colorscheme
  extras/konsole/light.colorscheme
Labels: assigned, documentation, enhancement

#41 Transparent mode enhacement
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/util.lua
Labels: assigned, documentation, enhancement

#42 Add proper `Description` inside `konsole` theme (bug from #33)
  CHANGELOG.md
  extras/iterm/dark.itermcolors
  extras/iterm/dimmed.itermcolors
  extras/iterm/light.itermcolors
  extras/konsole/dark.colorscheme
  extras/konsole/dimmed.colorscheme
  extras/konsole/light.colorscheme
  lua/github-theme/extra/init.lua
  lua/github-theme/extra/konsole.lua
Labels: assigned, documentation, enhancement

#43 lauline normal color fix
  lua/lualine/themes/github.lua
Labels: assigned, bug

#44 Area for messages and cmdline with `bold` text highlight
  CHANGELOG.md
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#46 `hideEndOfBuffer` options added
  CHANGELOG.md
  README.md
  lua/github-theme/colors.lua
  lua/github-theme/config.lua
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#47 Kitty Windows border color fixed
  Makefile
  extras/kitty/dark.conf
  extras/kitty/dimmed.conf
  extras/kitty/light.conf
  lua/github-theme/extra/kitty.lua
Labels: assigned

#48 `BufferLine` slant style separator color fixed ( related to #16)
  CHANGELOG.md
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#49 feat: `nvim-compe` plugin support
  CHANGELOG.md
  README.md
  lua/github-theme/config.lua
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#50 fix: Floating Windows background with `transparent` mode
  CHANGELOG.md
  lua/github-theme/colors.lua
Labels: assigned, documentation

#51 `barbar.nvim` plugins support
  CHANGELOG.md
  README.md
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement

#52 feat: hop.nvim plugin support
  CHANGELOG.md
  README.md
  lua/github-theme/theme.lua
Labels: assigned, documentation, enhancement
