Repository projekt0n/github-nvim-theme, pull requests merged in 2021-09, with the labels that each got.

#67 Set `NonText` & `EndOfBuffer` color value with `bg`
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: documentation, enhancement, assigned

#68 ✨ Add individual themes github-dark, github-dimmed and github-light
  colors/github-dark.lua
  colors/github-dimmed.lua
  colors/github-light.lua
Labels: enhancement, assigned

#70 docs: screenshot info
  README.md
Labels: documentation, assigned

#71 docs: lualine packer config added
  README.md
Labels: documentation, assigned

#75 fix: #72
  CHANGELOG.md
  colors/github.lua
Labels: documentation

#78 fix: #73
  CHANGELOG.md
  lua/github-theme/theme.lua
Labels: documentation, assigned

#79 fix: diagnostic highlights
  lua/github-theme/theme.lua
Labels: assigned

#81 fix: lualine colors with bg color support #80
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/lualine/themes/github.lua
Labels: documentation, assigned

#82 fix: #76
  CHANGELOG.md
  extras/alacritty/dark.yml
  extras/iterm/dark.itermcolors
  extras/kitty/dark.conf
  extras/konsole/dark.colorscheme
  lua/github-theme/colors.lua
Labels: documentation, assigned

#74 change NvimTreeIndentMarker
  lua/github-theme/theme.lua
Labels: enhancement, assigned

#87 refactor: `git_signs` & `dev_icons` colors with snake_case
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: documentation, assigned, refactor

#88 docs: sponsor added
  .github/FUNDING.yml
Labels: documentation, assigned

#90 docs: removed `lua` table assignment from `vim` example (related to #…
  CHANGELOG.md
  README.md
Labels: documentation, assigned

#91 feat: Github's default themes for `tmux`
  CHANGELOG.md
  Makefile
  README.md
  extras/tmux/dark.tmux
  extras/tmux/dark_default.tmux
  extras/tmux/dimmed.tmux
  extras/tmux/light.tmux
  extras/tmux/light_default.tmux
  lua/github-theme/extra/init.lua
  lua/github-theme/extra/tmux.lua
Labels: documentation, enhancement, assigned

#92 docs: colors override docs in `vim` config example
  README.md
Labels: documentation, assigned

#94 fix: Linting inside `tmux.lua`
  .luacheckrc
  CHANGELOG.md
  extras/tmux/dark.tmux
  extras/tmux/dark_default.tmux
  extras/tmux/dimmed.tmux
  extras/tmux/light.tmux
  extras/tmux/light_default.tmux
  lua/github-theme/extra/tmux.lua
Labels: documentation, assigned

#95 fix: NvimTree git highlight
  CHANGELOG.md
  lua/github-theme/colors.lua
  lua/github-theme/theme.lua
Labels: documentation, enhancement, assigned

#98 plugin support: nvim-compe and nvim-cmp
  CHANGELOG.md
  README.md
  lua/github-theme/theme.lua
Labels: documentation, enhancement, assigned
